// tests/schemaConventions.test.js
//
// Static lint over the committed schema dump (ref/database.sql). No database,
// no network — so it runs in CI, which has no DB credentials.
//
// WHY THIS EXISTS
//   The schema default is utf8mb4 / utf8mb4_general_ci. MySQL refuses
//   `column = column` comparisons across collations, so a table created with
//   a different one silently loses the ability to JOIN the core tables:
//
//     SELECT ... FROM trigger_executions t JOIN cases c ON c.case_id = t.case_id
//     -> ER_CANT_AGGREGATE_2COLLATIONS
//
//   It stays latent for a long time because `WHERE case_id = ?` never errors
//   (a bound literal is coercible and adopts the column's collation). Only
//   column-to-column joins fail — so the bug surfaces months later, in
//   whoever first tries to write a report across the two tables.
//
//   The trap: `DEFAULT CHARSET=utf8mb4` with no `COLLATE` does NOT inherit
//   the schema default. It falls back to the CHARSET default, which on
//   MySQL 8 is utf8mb4_0900_ai_ci. Omitting the clause entirely is correct.
//   26 of 129 tables were created this way before this test existed.
//
// KEEPING IT HONEST
//   ref/database.sql is generated by `npm run db:ref` and drift-checked by
//   `npm run db:ref:check`. This test is only as current as that dump — it
//   catches a bad CREATE TABLE that has been dumped, which is the state that
//   matters for the next person reading the schema.

'use strict';

const fs   = require('fs');
const path = require('path');

const DUMP     = path.join(__dirname, '..', 'ref', 'database.sql');
const EXPECTED = 'utf8mb4_general_ci';

// Tables knowingly left on another collation. Empty by intent: an entry here
// is a promise that every join against it goes through a numeric key. Add one
// only with a comment saying why, and expect to be asked about it.
const ALLOWED_EXCEPTIONS = new Set([]);

/** [{ table, collation }] for every CREATE TABLE in the dump. */
function parseTableCollations(sql) {
  const out = [];
  // The dump emits one `CREATE TABLE \`x\` (...) ENGINE=... COLLATE=y;` per
  // table, always with an explicit COLLATE=, so a line-oriented scan is enough.
  const createRe = /^CREATE TABLE `([^`]+)`/;
  const engineRe = /^\)\s*ENGINE=\w+(.*);$/;
  let current = null;
  for (const line of sql.split('\n')) {
    const c = createRe.exec(line);
    if (c) { current = c[1]; continue; }
    if (!current) continue;
    const e = engineRe.exec(line);
    if (e) {
      const m = /COLLATE=(\w+)/.exec(e[1]);
      out.push({ table: current, collation: m ? m[1] : null });
      current = null;
    }
  }
  return out;
}

describe('schema conventions (ref/database.sql)', () => {
  const sql = fs.readFileSync(DUMP, 'utf8');
  const tables = parseTableCollations(sql);

  test('the dump parsed and found a plausible number of tables', () => {
    // Guards against a dump-format change silently turning this suite into a
    // no-op that passes forever.
    expect(tables.length).toBeGreaterThan(50);
    expect(tables.every(t => t.collation)).toBe(true);
  });

  test(`every table uses ${EXPECTED}`, () => {
    const offenders = tables
      .filter(t => t.collation !== EXPECTED && !ALLOWED_EXCEPTIONS.has(t.table))
      .map(t => `  ${t.table}  ->  ${t.collation}`);

    expect(offenders.join('\n') || 'none').toBe('none');
    // If this failed: the table was created with `DEFAULT CHARSET=utf8mb4`
    // and no COLLATE. Fix with
    //   ALTER TABLE <t> CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
    // then re-run `npm run db:ref`. See ref/2026-08-17_collation_normalize.sql.
  });
});
