// tests/schemaConventions.test.js
//
// Static lint over the committed schema dump (ref/database.sql). No database,
// no network — so it runs in CI, which has no DB credentials.
//
// WHY THIS EXISTS
//   The schema default is utf8mb4 / utf8mb4_general_ci. MySQL refuses
//   `column = column` comparisons across collations, so a table created with
//   a different one silently loses the ability to JOIN the core tables:
//
//     SELECT ... FROM trigger_executions t JOIN cases c ON c.case_id = t.case_id
//     -> ER_CANT_AGGREGATE_2COLLATIONS
//
//   It stays latent for a long time because `WHERE case_id = ?` never errors
//   (a bound literal is coercible and adopts the column's collation). Only
//   column-to-column joins fail — so the bug surfaces months later, in
//   whoever first tries to write a report across the two tables.
//
//   The trap: `DEFAULT CHARSET=utf8mb4` with no `COLLATE` does NOT inherit
//   the schema default. It falls back to the CHARSET default, which on
//   MySQL 8 is utf8mb4_0900_ai_ci. Omitting the clause entirely is correct.
//   26 of 129 tables were created this way before this test existed.
//
// KEEPING IT HONEST
//   ref/database.sql is generated by `npm run db:ref` and drift-checked by
//   `npm run db:ref:check`. This test is only as current as that dump — it
//   catches a bad CREATE TABLE that has been dumped, which is the state that
//   matters for the next person reading the schema.

'use strict';

const fs   = require('fs');
const path = require('path');

const DUMP     = path.join(__dirname, '..', 'ref', 'database.sql');
const EXPECTED = 'utf8mb4_general_ci';

// Tables knowingly left on another collation. Empty by intent: an entry here
// is a promise that every join against it goes through a numeric key. Add one
// only with a comment saying why, and expect to be asked about it.
const ALLOWED_EXCEPTIONS = new Set([]);

/** [{ table, collation }] for every CREATE TABLE in the dump. */
function parseTableCollations(sql) {
  const out = [];
  // The dump emits one `CREATE TABLE \`x\` (...) ENGINE=... COLLATE=y;` per
  // table, always with an explicit COLLATE=, so a line-oriented scan is enough.
  const createRe = /^CREATE TABLE `([^`]+)`/;
  const engineRe = /^\)\s*ENGINE=\w+(.*);$/;
  let current = null;
  for (const line of sql.split('\n')) {
    const c = createRe.exec(line);
    if (c) { current = c[1]; continue; }
    if (!current) continue;
    const e = engineRe.exec(line);
    if (e) {
      const m = /COLLATE=(\w+)/.exec(e[1]);
      out.push({ table: current, collation: m ? m[1] : null });
      current = null;
    }
  }
  return out;
}

describe('schema conventions (ref/database.sql)', () => {
  const sql = fs.readFileSync(DUMP, 'utf8');
  const tables = parseTableCollations(sql);

  test('the dump parsed and found a plausible number of tables', () => {
    // Guards against a dump-format change silently turning this suite into a
    // no-op that passes forever.
    expect(tables.length).toBeGreaterThan(50);
    expect(tables.every(t => t.collation)).toBe(true);
  });

  test(`every table uses ${EXPECTED}`, () => {
    const offenders = tables
      .filter(t => t.collation !== EXPECTED && !ALLOWED_EXCEPTIONS.has(t.table))
      .map(t => `  ${t.table}  ->  ${t.collation}`);

    expect(offenders.join('\n') || 'none').toBe('none');
    // If this failed: the table was created with `DEFAULT CHARSET=utf8mb4`
    // and no COLLATE. Fix with
    //   ALTER TABLE <t> CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
    // then re-run `npm run db:ref`. See ref/2026-08-17_collation_normalize.sql.
  });
});

// ═════════════════════════════════════════════════════════════════════════════
// COLUMN-LEVEL: cases.case_dropbox
//
// The suite above lints TABLE collations. This block lints ONE COLUMN, and it
// exists because of the specific shape of the change that widened it.
//
// `ALTER TABLE ... MODIFY` restates a column's ENTIRE definition. Every
// attribute you do not repeat is dropped and re-derived from the table default:
// charset, collation, nullability, default, comment. The obvious form —
//
//     ALTER TABLE cases MODIFY case_dropbox VARCHAR(512) NULL;
//
// happens to be harmless here only because `cases` defaults to utf8mb4 /
// utf8mb4_general_ci, which is what the column already carried. Change the
// table default one day, or copy that MODIFY to a table that never had one, and
// the same statement silently re-collates the column — the exact failure this
// file's header describes, arriving through a different door. So the shipped
// ALTER names every attribute, and this test is the fence that keeps it that way.
//
// ⚠️ RED UNTIL THE DDL RUNS. This reads the committed dump, so it goes green
// only after the ALTER is applied AND `npm run db:ref` regenerates
// ref/database.sql. Deploy order is SQL first; regenerating the dump is part of
// applying it.
describe('cases.case_dropbox — the widened column keeps every other attribute', () => {
  const sql = fs.readFileSync(DUMP, 'utf8');

  /** The column's line out of the dump, verbatim. */
  function columnLine(table, column) {
    const start = sql.indexOf(`CREATE TABLE \`${table}\``);
    if (start === -1) return null;
    const end = sql.indexOf('\n) ENGINE=', start);
    const body = sql.slice(start, end === -1 ? undefined : end);
    for (const line of body.split('\n')) {
      if (line.trim().startsWith(`\`${column}\``)) return line.trim().replace(/,$/, '');
    }
    return null;
  }

  const line = columnLine('cases', 'case_dropbox');

  test('the column is present in the dump (guards this block from rotting)', () => {
    expect(line).toBeTruthy();
  });

  test('it is VARCHAR(512) — widened so a valid link is never rejected as too long', () => {
    // 255 was the original. The guard in documentSyncService rejects rather
    // than clamps, so a column narrower than a real Dropbox link turns a
    // correct confirm into a 500. Longest live value is 125; 512 is headroom.
    expect(line).toMatch(/varchar\(512\)/i);
  });

  test('CHARACTER SET and COLLATE survived the MODIFY, spelled out', () => {
    // Explicit, not inherited. `case_id` joins against this table constantly
    // and a re-collated column is a join that fails months later.
    expect(line).toMatch(/CHARACTER SET utf8mb4/i);
    expect(line).toMatch(/COLLATE utf8mb4_general_ci/i);
  });

  test('it is still nullable with a NULL default', () => {
    // 33 of 1,074 cases have no Dropbox folder. NOT NULL here would break case
    // creation, which sets ~4 columns and leans on defaults for the rest.
    expect(line).toMatch(/DEFAULT NULL/i);
    expect(line).not.toMatch(/\bNOT NULL\b/i);
  });

  test('the application guard agrees with the column', () => {
    // Two numbers that must not drift: the column width and the reject
    // threshold. If they disagree, either valid links 500 or truncated ones
    // reach the column silently (no STRICT_TRANS_TABLES to catch it).
    const width = Number(/varchar\((\d+)\)/i.exec(line)[1]);
    const sync = require('../services/documentSyncService');
    expect(sync.CASE_DROPBOX_MAX).toBe(width);
  });

  test('the curated report manifest declares the same type', () => {
    // manifest.js is prose the AI report author reads as fact. Nothing
    // validates it against the schema, so it drifts silently unless something
    // like this asks.
    const { TABLES } = require('../lib/reportSchema/manifest');
    expect(TABLES.cases.columns.case_dropbox.type).toBe('varchar(512)');
  });
});
