-- ─────────────────────────────────────────────────────────────────────────────
-- 2026-09-01 — Unified Events U2: item-type registry + type_key on appts/events
-- ref/2026-09-01_unified_events_u2.sql
--
-- Governing design: ref/UNIFIED_EVENTS_DESIGN_V0_5.md §3.3 (A1), §3.3.2, §7 (U2),
-- §7.1, Appendix A. Worker: Fable. Slice owner: CAL. Rulings 2026-09-01 (Fred):
-- D1 enum order = the column's; D5 no ci-redundant aliases; R1–R4 as applied
-- in the backend.
--
-- WHY
--   Every write path mints free-text type strings and every consumer matches
--   them (v0.5 §3.3). This slice makes "what a calendar item IS" data:
--
--   1. calendar_item_types — the registry. One row per type, for appts and
--      events alike. `kind` decides storage under §3.3.2 (meeting → appts,
--      else → events). `singleton`, `blocks_default`, `client_attends` are
--      DATA ONLY in this slice — nothing enforces them until U6. `active`
--      gates PICKERS only; an inactive type ('test') still resolves.
--
--   2. type_key VARCHAR(40) NULL on BOTH tables, no FK. An unknown key must
--      be storable (raw passthrough) and the registry is data staff will
--      edit; integrity is asserted by VERIFY 4, not the engine (events/appts
--      carry zero FKs — E0a convention).
--
--   3. Backfill from the E1 vocabulary, GENERATED by scripts/genTypeKeyBackfill.js
--      from caseEventService._EVENT_TYPE_KEYS / _APPT_TYPE_KEYS /
--      _EVENT_ROW_OVERRIDES. tests/genTypeKeyBackfill.test.js asserts the
--      committed blocks equal a fresh regeneration — the migration cannot
--      drift from E1's derivation, so no row changes key when U3 swaps E1 to
--      read the column.
--
-- ── ORDER OF OPERATIONS ─────────────────────────────────────────────────────
--   1. THIS FILE, top to bottom: A.1 CREATE TABLE → A.2 seed → A.3 ALTERs →
--      A.4 backfill. Then run the VERIFY block.
--   2. Deploy the BACKEND (createEvent/createAppt/PATCH paths write type_key
--      + kind from the registry). Rows created between step 1 and 2 have
--      type_key NULL: RE-RUN the A.4 generated block once (idempotent), then
--      VERIFY 1–2 again → 0 / 0.
--   3. Deploy the FRONTEND (eventform.html registry picker + apptform2 key display).
--
--   SQL-first is safe: the new table and columns are unread and unwritten by
--   the currently-deployed backend. Deploying the backend FIRST would 500
--   every createEvent/createAppt (INSERT names a column that does not
--   exist) — do not reverse the order.
--
--   No session variables, no LAST_INSERT_ID, no stored procedures, no
--   cross-statement transaction. Every statement is standalone and may run on
--   its own pooled connection (the DB-console convention; E0a header).
--
-- ── RE-RUN SAFETY ───────────────────────────────────────────────────────────
--   A.1 CREATE TABLE IF NOT EXISTS   — idempotent.
--   A.2 seed                         — idempotent (ON DUPLICATE KEY UPDATE label only).
--   A.3 ALTERs                       — NOT idempotent and cannot be: MySQL 8.4 has
--       no "ADD COLUMN IF NOT EXISTS" and the house forbids stored procedures /
--       session variables in migrations. House convention (E0a, R4, pipeline_lane):
--       plain ALTER + this note. A re-run fails with ER_DUP_FIELDNAME
--       ("Duplicate column name 'type_key'") / ER_DUP_KEYNAME, which MEANS the
--       statement is already applied — SKIP it and continue. To check first:
--         SELECT TABLE_NAME, COLUMN_NAME FROM information_schema.COLUMNS
--          WHERE TABLE_SCHEMA = DATABASE() AND COLUMN_NAME = 'type_key'
--            AND TABLE_NAME IN ('events','appts');
--       (expects 0 rows before A.3, 2 rows after).
--   A.4 backfill                     — idempotent (`WHERE type_key IS NULL` on
--       every bulk statement; the four row overrides re-write the same value).
--
-- ── COLLATION ───────────────────────────────────────────────────────────────
--   House collation utf8mb4_general_ci, spelled out on the TABLE and on every
--   new VARCHAR column. A bare `DEFAULT CHARSET=utf8mb4` yields 0900_ai_ci on
--   MySQL 8 and breaks joins against events/appts (tests/schemaConventions).
--   `kind` ENUM is byte-identical to events.kind (E0a):
--   ('hearing','meeting','deadline','conference','other') — the COLUMN's order,
--   not the v0.5 §3.3 listing (CAL corrects the doc at U3).
--
-- ── sql_mode NOTE ───────────────────────────────────────────────────────────
--   The session lacks STRICT_TRANS_TABLES: an invalid ENUM write lands as ''
--   silently. Everything here writes ENUMs as bare literals from the seed, and
--   the backend validates `kind` against the registry (which carries the same
--   ENUM) before binding. VERIFY 5 is the check that no '' kind exists.
--
-- ── ROLLBACK ────────────────────────────────────────────────────────────────
--   Redeploy the previous backend FIRST (it INSERTs kind/type_key by name),
--   then:
--     ALTER TABLE events DROP KEY idx_events_type_key;
--     ALTER TABLE events DROP COLUMN type_key;
--     ALTER TABLE appts  DROP KEY idx_appts_type_key;
--     ALTER TABLE appts  DROP COLUMN type_key;
--     DROP TABLE calendar_item_types;
--   The A.4 block also re-ran the E0b kind statements; those are E0b state
--   and are NOT rolled back here (see E0b's own rollback). No other table is
--   written by this file.
--
-- After running: regenerate the schema snapshot via
--   POST /admin/db/schema/save-to-ref
-- (ref/database.sql is auto-generated — do not hand-edit it.)
-- ─────────────────────────────────────────────────────────────────────────────


-- ═════════════════════════════════════════════════════════════════════════════
-- A.1 — the registry
-- ═════════════════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS calendar_item_types (
  type_key        VARCHAR(40)  CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  label           VARCHAR(80)  CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  kind            ENUM('hearing','meeting','deadline','conference','other') NOT NULL
                  COMMENT 'byte-identical to events.kind (E0a). meeting → appts, else → events (v0.5 §3.3.2).',
  singleton       TINYINT(1)   NOT NULL DEFAULT 0
                  COMMENT 'U2: data only. Enforced by the U6 write API behind unified_singleton_enabled.',
  blocks_default  ENUM('attendee','firm','none') NOT NULL DEFAULT 'attendee'
                  COMMENT 'U2: data only (was court_item_policy.blocks). Read at U6/U7.',
  client_attends  TINYINT(1)   NOT NULL DEFAULT 0
                  COMMENT 'U2: data only (was court_item_policy.attendance). Read at U6/U7.',
  default_length  SMALLINT     NULL COMMENT 'minutes; court_v2 schema_gaps duration lands here (U7)',
  ingest_aliases  JSON         NULL COMMENT 'inbound free text → this key, WRITE TIME ONLY; never the row''s own label (ci)',
  case_types      JSON         NULL COMMENT 'picker scoping; NULL = all case types',
  active          TINYINT(1)   NOT NULL DEFAULT 1 COMMENT 'gates pickers only; inactive types still resolve',
  sort_order      INT          NOT NULL DEFAULT 0,
  created_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (type_key),
  KEY idx_cit_kind_active (kind, active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- ═════════════════════════════════════════════════════════════════════════════
-- A.2 — seed (GENERATED — do not hand-edit; edit scripts/calendarTypeSeed.js and
--       run `node scripts/genTypeKeyBackfill.js --write`)
-- ═════════════════════════════════════════════════════════════════════════════
-- BEGIN GENERATED seed (scripts/genTypeKeyBackfill.js)
-- calendar_item_types seed — ONE statement, re-runnable. The row-alias form of
-- ON DUPLICATE KEY UPDATE (MySQL ≥ 8.0.19; VALUES() in ODKU is deprecated) touches
-- ONLY label on re-run, so live edits to the policy columns are never overwritten.
-- 34 rows. Source: scripts/calendarTypeSeed.js.
INSERT INTO calendar_item_types
  (type_key, label, kind, singleton, blocks_default, client_attends, default_length, ingest_aliases, case_types, active, sort_order)
VALUES
  ('iss', 'Initial Strategy Session', 'meeting', 0, 'attendee', 1, 15, '["Intial Strategy Session"]', NULL, 1, 10),
  ('ss', 'Strategy Session', 'meeting', 0, 'attendee', 1, 15, '[]', NULL, 1, 20),
  ('ss_follow_up', 'Strategy Session Follow Up', 'meeting', 0, 'attendee', 1, 15, '["Follow Up"]', NULL, 1, 30),
  ('consultation', 'Consultation', 'meeting', 0, 'attendee', 1, 30, '[]', NULL, 1, 40),
  ('pre_filing', 'Pre-Filing Meeting', 'meeting', 0, 'attendee', 1, 30, '["Pre-filing (30 min)"]', '["Bankruptcy"]', 1, 50),
  ('meeting_341', '341 Meeting', 'meeting', 1, 'attendee', 1, 10, '["341"]', '["Bankruptcy"]', 1, 60),
  ('schedules_meeting', 'Schedules Completion Meeting', 'meeting', 0, 'attendee', 1, 45, '[]', '["Bankruptcy"]', 1, 70),
  ('docs_meeting', 'Documents Completion Meeting', 'meeting', 0, 'attendee', 1, 30, '[]', '["Bankruptcy"]', 1, 80),
  ('matrix_meeting', 'Matrix Completion Meeting', 'meeting', 0, 'attendee', 1, 30, '[]', '["Bankruptcy"]', 1, 90),
  ('pre_lawsuit', 'Pre-Lawsuit Meeting', 'meeting', 0, 'attendee', 1, 30, '["Pre Lawsuit Meeting"]', '["Civil Litigation"]', 1, 100),
  ('tax_consult', 'Tax Consult', 'meeting', 0, 'attendee', 1, 30, '["Tax Consultation"]', NULL, 1, 110),
  ('meeting', 'Meeting', 'meeting', 0, 'attendee', 1, 15, '["to go over claims","to go over objections to Chapt","Case Status Review"]', NULL, 1, 120),
  ('confirmation_hearing', 'Confirmation Hearing', 'hearing', 1, 'attendee', 0, 30, '[]', '["Bankruptcy"]', 1, 200),
  ('show_cause', 'Show Cause Hearing', 'hearing', 1, 'none', 0, 30, '["Show Cause"]', '["Bankruptcy"]', 1, 210),
  ('hearing', 'Hearing', 'hearing', 0, 'attendee', 0, 30, '["Court Date"]', NULL, 1, 220),
  ('trial', 'Trial', 'hearing', 0, 'attendee', 0, NULL, '["Trial / Pre-Trial Hearing"]', NULL, 1, 230),
  ('status_conference', 'Status Conference', 'conference', 0, 'attendee', 0, 30, '["Telephonic Status Conference"]', NULL, 1, 300),
  ('scheduling_conference', 'Initial Scheduling Conference', 'conference', 0, 'attendee', 0, 30, '[]', NULL, 1, 310),
  ('pretrial_conference', 'Pre-trial Conference', 'conference', 0, 'attendee', 0, 30, '[]', NULL, 1, 320),
  ('deposition', 'Deposition', 'conference', 0, 'attendee', 1, 240, '[]', NULL, 1, 330),
  ('docs_deadline', 'Docs Deadline', 'deadline', 1, 'none', 0, NULL, '[]', '["Bankruptcy"]', 1, 400),
  ('schedules_deadline', 'Schedules Deadline', 'deadline', 1, 'none', 0, NULL, '[]', '["Bankruptcy"]', 1, 410),
  ('dischargeability_due', 'Dischargeability Deadline', 'deadline', 1, 'none', 0, NULL, '[]', '["Bankruptcy"]', 1, 420),
  ('object_confirmation_due', 'Objection to Confirmation Deadline', 'deadline', 1, 'none', 0, NULL, '[]', '["Bankruptcy"]', 1, 430),
  ('poc_due', 'Proof of Claim Deadline', 'deadline', 1, 'none', 0, NULL, '[]', '["Bankruptcy"]', 1, 440),
  ('poc_gov_due', 'Governmental Proof of Claim Deadline', 'deadline', 1, 'none', 0, NULL, '[]', '["Bankruptcy"]', 1, 450),
  ('confirmation_certificate_deadline', 'Confirmation Certificate Deadline', 'deadline', 1, 'none', 0, NULL, '[]', '["Bankruptcy"]', 1, 460),
  ('filing_fee_deadline', 'Filing Fee Deadline', 'deadline', 1, 'none', 0, NULL, '[]', '["Bankruptcy"]', 1, 470),
  ('filing_fee_installment_deadline', 'Filing Fee Installment Deadline', 'deadline', 0, 'none', 0, NULL, '[]', '["Bankruptcy"]', 1, 480),
  ('deadline', 'Deadline', 'deadline', 0, 'none', 0, NULL, '[]', NULL, 1, 490),
  ('order', 'Order', 'other', 0, 'none', 0, NULL, '[]', NULL, 1, 500),
  ('milestone', 'Milestone', 'other', 0, 'none', 0, NULL, '[]', NULL, 1, 510),
  ('internal', 'Internal', 'other', 0, 'firm', 0, NULL, '[]', NULL, 1, 520),
  ('test', 'Test', 'other', 0, 'none', 0, NULL, '["test appt","test2 appt","test3 appt","Test Appointment","Pizza Party","bug hunting Session","Repetitive Session","Potato Hunting"]', NULL, 0, 999)
AS new
ON DUPLICATE KEY UPDATE label = new.label;
-- END GENERATED seed


-- ═════════════════════════════════════════════════════════════════════════════
-- A.3 — type_key on both tables (plain ALTERs; on re-run skip "Duplicate column")
-- ═════════════════════════════════════════════════════════════════════════════
ALTER TABLE events
  ADD COLUMN type_key VARCHAR(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL
    COMMENT 'U2: calendar_item_types.type_key (by value, no FK). NULL = unresolved/raw passthrough or pre-backfill.'
    AFTER kind;

ALTER TABLE events
  ADD KEY idx_events_type_key (type_key);

ALTER TABLE appts
  ADD COLUMN type_key VARCHAR(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL
    COMMENT 'U2: calendar_item_types.type_key (by value, no FK). NULL = appt_type NULL, unresolved, or pre-backfill.'
    AFTER appt_type;

ALTER TABLE appts
  ADD KEY idx_appts_type_key (type_key);


-- ═════════════════════════════════════════════════════════════════════════════
-- A.4 — backfill (GENERATED from caseEventService (E1) — do not hand-edit; run
--       `node scripts/genTypeKeyBackfill.js --write`). Re-run this whole block
--       once after the backend deploy.
-- ═════════════════════════════════════════════════════════════════════════════
-- BEGIN GENERATED backfill (scripts/genTypeKeyBackfill.js)
-- Raws below are caseEventService (E1) NORMALIZED lookup keys — trim+lowercase.
-- events.event_type / appts.appt_type are utf8mb4_general_ci, so each IN-list matches
-- every live spelling variant of that type. Every statement is guarded by
-- `type_key IS NULL` and is therefore idempotent; re-run the whole block after the
-- backend deploy to catch rows created in between.

-- events.type_key by event_type  (caseEventService._EVENT_TYPE_KEYS)
UPDATE events SET type_key = 'meeting_341' WHERE type_key IS NULL AND event_type = '341';
UPDATE events SET type_key = 'confirmation_hearing' WHERE type_key IS NULL AND event_type IN ('confirmation hearing', 'confirmation_hearing');
UPDATE events SET type_key = 'hearing' WHERE type_key IS NULL AND event_type = 'hearing';
UPDATE events SET type_key = 'show_cause' WHERE type_key IS NULL AND event_type IN ('show cause', 'show cause hearing');
UPDATE events SET type_key = 'trial' WHERE type_key IS NULL AND event_type IN ('trial', 'trial / pre-trial hearing');
UPDATE events SET type_key = 'status_conference' WHERE type_key IS NULL AND event_type IN ('telephonic status conference', 'status conference');
UPDATE events SET type_key = 'scheduling_conference' WHERE type_key IS NULL AND event_type = 'initial scheduling conference';
UPDATE events SET type_key = 'pretrial_conference' WHERE type_key IS NULL AND event_type = 'pre-trial conference';
UPDATE events SET type_key = 'deposition' WHERE type_key IS NULL AND event_type = 'deposition';
UPDATE events SET type_key = 'dischargeability_due' WHERE type_key IS NULL AND event_type = 'dischargeability_due';
UPDATE events SET type_key = 'object_confirmation_due' WHERE type_key IS NULL AND event_type = 'object_confirmation_due';
UPDATE events SET type_key = 'poc_due' WHERE type_key IS NULL AND event_type = 'poc_due';
UPDATE events SET type_key = 'poc_gov_due' WHERE type_key IS NULL AND event_type = 'poc_gov_due';
UPDATE events SET type_key = 'docs_deadline' WHERE type_key IS NULL AND event_type = 'docs deadline';
UPDATE events SET type_key = 'schedules_deadline' WHERE type_key IS NULL AND event_type = 'schedules deadline';
UPDATE events SET type_key = 'confirmation_certificate_deadline' WHERE type_key IS NULL AND event_type = 'confirmation certificate deadline';
UPDATE events SET type_key = 'filing_fee_deadline' WHERE type_key IS NULL AND event_type = 'filing fee deadline';
UPDATE events SET type_key = 'filing_fee_installment_deadline' WHERE type_key IS NULL AND event_type = 'filing fee installment deadline';
UPDATE events SET type_key = 'deadline' WHERE type_key IS NULL AND event_type = 'deadline';
UPDATE events SET type_key = 'order' WHERE type_key IS NULL AND event_type = 'order';
UPDATE events SET type_key = 'milestone' WHERE type_key IS NULL AND event_type = 'milestone';

-- events row overrides by id  (caseEventService._EVENT_ROW_OVERRIDES; unguarded so
-- they win over the bulk statements — a re-run writes the same value)
UPDATE events SET type_key = 'test' WHERE event_id = 4 AND event_type = 'Milestone';
UPDATE events SET type_key = 'test' WHERE event_id = 6 AND event_type = 'Deadline';
UPDATE events SET type_key = 'filing_fee_deadline' WHERE event_id = 107 AND event_type = 'Order';
UPDATE events SET type_key = 'trial' WHERE event_id = 134 AND event_type = 'Trial / Pre-Trial Hearing';

-- appts.type_key by appt_type  (caseEventService._APPT_TYPE_KEYS; the literal 'None'
-- entry is skipped — 0 live rows — and appt_type IS NULL rows stay type_key NULL by
-- ruling, v0.5 §8.1)
UPDATE appts SET type_key = 'iss' WHERE type_key IS NULL AND appt_type IN ('initial strategy session', 'intial strategy session');
UPDATE appts SET type_key = 'ss' WHERE type_key IS NULL AND appt_type = 'strategy session';
UPDATE appts SET type_key = 'ss_follow_up' WHERE type_key IS NULL AND appt_type IN ('strategy session follow up', 'follow up');
UPDATE appts SET type_key = 'pre_filing' WHERE type_key IS NULL AND appt_type IN ('pre-filing meeting', 'pre-filing (30 min)');
UPDATE appts SET type_key = 'meeting_341' WHERE type_key IS NULL AND appt_type = '341 meeting';
UPDATE appts SET type_key = 'schedules_meeting' WHERE type_key IS NULL AND appt_type = 'schedules completion meeting';
UPDATE appts SET type_key = 'docs_meeting' WHERE type_key IS NULL AND appt_type = 'documents completion meeting';
UPDATE appts SET type_key = 'matrix_meeting' WHERE type_key IS NULL AND appt_type = 'matrix completion meeting';
UPDATE appts SET type_key = 'meeting' WHERE type_key IS NULL AND appt_type IN ('meeting', 'to go over claims', 'to go over objections to chapt', 'case status review');
UPDATE appts SET type_key = 'consultation' WHERE type_key IS NULL AND appt_type = 'consultation';
UPDATE appts SET type_key = 'pre_lawsuit' WHERE type_key IS NULL AND appt_type IN ('pre-lawsuit meeting', 'pre lawsuit meeting');
UPDATE appts SET type_key = 'tax_consult' WHERE type_key IS NULL AND appt_type = 'tax consult';
UPDATE appts SET type_key = 'test' WHERE type_key IS NULL AND appt_type IN ('test', 'test appt', 'test2 appt', 'test3 appt', 'test appointment', 'pizza party', 'bug hunting session', 'repetitive session');

-- events.kind for rows created between the E0b apply and the U2 backend deploy —
-- the five U1/E0b bulk statements VERBATIM (ref/2026-09-01_unified_events_e0b.sql)
UPDATE events SET kind = 'hearing'
 WHERE kind IS NULL
   AND event_type IN ('Confirmation Hearing','confirmation_hearing','Hearing',
                      'Show Cause','Show Cause Hearing','Trial','Trial / Pre-Trial Hearing');

UPDATE events SET kind = 'conference'
 WHERE kind IS NULL
   AND event_type IN ('Telephonic Status Conference','Status Conference',
                      'Initial Scheduling Conference','Pre-trial Conference','Deposition');

UPDATE events SET kind = 'meeting'
 WHERE kind IS NULL
   AND event_type = '341';

UPDATE events SET kind = 'deadline'
 WHERE kind IS NULL
   AND event_type IN ('dischargeability_due','object_confirmation_due','poc_due','poc_gov_due',
                      'Docs Deadline','Schedules Deadline','Confirmation Certificate Deadline',
                      'Filing Fee Deadline','Filing Fee Installment Deadline','Deadline');

UPDATE events SET kind = 'other'
 WHERE kind IS NULL
   AND event_type IN ('Order','Milestone');
-- END GENERATED backfill


-- ═════════════════════════════════════════════════════════════════════════════
-- VERIFY (run after A.4; expected values re-derived from the live BINARY census
--         2026-09-01 — events 155 rows, appts 2,217 rows. Rows created since
--         shift the per-key counts by their type; the BLOCKING gates are the
--         zero-counts.)
-- ═════════════════════════════════════════════════════════════════════════════

-- 1. BLOCKING — every event has a key. Expect 0.
SELECT COUNT(*) AS events_type_key_null FROM events WHERE type_key IS NULL;

-- 2. BLOCKING — every typed appt has a key. Expect 0.
SELECT COUNT(*) AS appts_type_key_null_non_null_type
  FROM appts WHERE type_key IS NULL AND appt_type IS NOT NULL;

-- 3. informational — the 8 untyped appts stay NULL by ruling (v0.5 §8.1). Expect 8 / 8.
SELECT COUNT(*) AS appts_null_type, SUM(type_key IS NULL) AS of_which_key_null
  FROM appts WHERE appt_type IS NULL;

-- 4. BLOCKING — no key on either table is absent from the registry. Expect 0.
SELECT COUNT(*) AS unknown_keys FROM (
  SELECT type_key FROM events WHERE type_key IS NOT NULL
  UNION ALL
  SELECT type_key FROM appts  WHERE type_key IS NOT NULL) t
 WHERE type_key NOT IN (SELECT type_key FROM calendar_item_types);

-- 5. BLOCKING — events.kind agrees with the registry's kind for that key, and no
--    '' kind slipped in under the non-strict sql_mode. Expect 0 rows.
SELECT e.type_key, e.kind, c.kind AS registry_kind, COUNT(*) AS n
  FROM events e
  JOIN calendar_item_types c ON c.type_key = e.type_key
 WHERE e.kind IS NULL OR e.kind = '' OR CAST(e.kind AS CHAR) <> CAST(c.kind AS CHAR)
 GROUP BY e.type_key, e.kind, c.kind;

-- 6. appts by key (BINARY census 2026-09-01, 2,217 rows):
--    iss 925 · pre_filing 332 · ss 276 · meeting_341 241 · ss_follow_up 174
--    · schedules_meeting 122 · meeting 116 · test 9 · NULL 8 · consultation 7
--    · pre_lawsuit 3 · tax_consult 2 · docs_meeting 1 · matrix_meeting 1
SELECT type_key, COUNT(*) AS n FROM appts GROUP BY type_key ORDER BY n DESC, type_key;

-- 7. events by key (census 2026-09-01, 155 rows):
--    confirmation_hearing 30 · meeting_341 16 · dischargeability_due 16 · hearing 14
--    · docs_deadline 13 · schedules_deadline 11 · confirmation_certificate_deadline 10
--    · object_confirmation_due 9 · poc_due 9 · poc_gov_due 9 · show_cause 4
--    · deadline 2 · filing_fee_deadline 2 · status_conference 2 · test 2 · trial 2
--    · deposition 1 · filing_fee_installment_deadline 1 · pretrial_conference 1
--    · scheduling_conference 1
--    (order 0 and milestone 0 — their only live rows are overrides 107 → filing_fee_deadline, 4 → test)
SELECT type_key, COUNT(*) AS n FROM events GROUP BY type_key ORDER BY n DESC, type_key;

-- 8. the four overrides landed. Expect: 4 test · 6 test · 107 filing_fee_deadline · 134 trial
SELECT event_id, event_type, kind, type_key, event_status
  FROM events WHERE event_id IN (4, 6, 107, 134) ORDER BY event_id;

-- 9. registry row count. Expect 34.
SELECT COUNT(*) AS registry_rows FROM calendar_item_types;

-- 10. the registry's ENUM is byte-identical to events.kind. Expect ONE row (both columns
--     the same COLUMN_TYPE string) — two rows means the enums differ.
SELECT COLUMN_TYPE, COUNT(*) AS n
  FROM information_schema.COLUMNS
 WHERE TABLE_SCHEMA = DATABASE()
   AND ((TABLE_NAME = 'events' AND COLUMN_NAME = 'kind')
     OR (TABLE_NAME = 'calendar_item_types' AND COLUMN_NAME = 'kind'))
 GROUP BY COLUMN_TYPE;


-- ── POST-DEPLOY GATES (Fred, readonly, after backend + frontend) ─────────────
-- G1. no new event lands without a key (replace <deploy ts>). Expect 0.
--   SELECT COUNT(*) FROM events WHERE type_key IS NULL AND event_create_date > '<deploy ts>';
-- G2. same for appts. Expect 0.
--   SELECT COUNT(*) FROM appts WHERE type_key IS NULL AND appt_type IS NOT NULL AND appt_create_date > '<deploy ts>';
-- G3. eventform: create a Confirmation Hearing → newest row type_key='confirmation_hearing', kind='hearing'.
--   SELECT event_id, event_type, kind, type_key FROM events ORDER BY event_id DESC LIMIT 3;
-- G4. book the `consult` view → appt type_key='consultation'.
--   SELECT appt_id, appt_type, type_key FROM appts ORDER BY appt_id DESC LIMIT 3;
-- G5. open an existing event in eventform, save unchanged → event_updated_at unchanged.
-- G6. GET /api/case-events/<case> before vs after — identical (E1 still derives from strings).
-- ─────────────────────────────────────────────────────────────────────────────
